# Author: Peter5930
# Github located here: https://github.com/Peter5930/protadjust

prot_1_modifier: 0.03
prot_2_modifier: 0.05
prot_3_modifier: 0.09
prot_4_modifier: 0.115
thorns_effect_type: WITHER
thorns_effect_duration: 150
thorns_effect_intensity: 0
buff_dispenser_damage: true
dispenser_arrow_damage: 18
dispenser_flame_arrows_ticks: 500
dispenser_arrow_velocity_multiplier: 3.5
dispenser_arrow_spread_multiplier: 3.0
BLOCK_EXPLOSION_global_modifier: 2.0
CONTACT_global_modifier: 1.0
DROWNING_global_modifier: 1.0
ENTITY_ATTACK_global_modifier: 1.0
ENTITY_EXPLOSION_global_modifier: 1.0
FALL_global_modifier: 1.0
FALLING_BLOCK_global_modifier: 1.0
FIRE_global_modifier: 1.0
FIRE_TICK_global_modifier: 1.0
LAVA_global_modifier: 1.0
LIGHTNING_global_modifier: 1.0
MAGIC_global_modifier: 1.0
MELTING_global_modifier: 1.0
POISON_global_modifier: 0.45
PROJECTILE_global_modifier: 1.0
STARVATION_global_modifier: 1.0
SUFFOCATION_global_modifier: 1.0
SUICIDE_global_modifier: 1.0
THORNS_global_modifier: 1.0
VOID_global_modifier: 1.0
BLOCK_EXPLOSION_prot_modifier: 1.0
CONTACT_prot_modifier: 1.0
DROWNING_prot_modifier: 1.0
ENTITY_ATTACK_prot_modifier: 0.0
ENTITY_EXPLOSION_prot_modifier: 1.0
FALL_prot_modifier: 1.0
FALLING_BLOCK_prot_modifier: 1.0
FIRE_prot_modifier: 1.0
FIRE_TICK_prot_modifier: 1.0
LAVA_prot_modifier: 1.0
LIGHTNING_prot_modifier: 1.0
MAGIC_prot_modifier: 1.0
MELTING_prot_modifier: 1.0
POISON_prot_modifier: 3.0
PROJECTILE_prot_modifier: 1.0
STARVATION_prot_modifier: 1.0
SUFFOCATION_prot_modifier: 1.0
SUICIDE_prot_modifier: 1.0
THORNS_prot_modifier: 1.0
VOID_prot_modifier: 1.0
